### ISSUE TITLE
austin-tui now on conda-forge

### ISSUE THREAD

**Issue by siboehm** [P403n1x87/austin-tui#17]
Just FYI, I've packaged `austin-tui` (and `austin-python`) on conda-forge, so now `conda install -c conda-forge austin-tui` is probably the most convenient way to install austin-tui.

@P403n1x87 let me know if you want to be a maintainer on the feedstock, I can always add you :) Thanks for creating this package, austin is great!

**Comment by P403n1x87** [comment]
:raised_hands: That's awesome, @siboehm! Thank you so much for taking the time to do this. Feel free to open a PR to add to the installation instructions on the README! :smile:
