### ISSUE TITLE
Unable to decrease threshold

### ISSUE THREAD

**Issue by darrenburns** [P403n1x87/austin-tui#21]
### Description

Pressing `-` doesn't increase the threshold. Nothing happens.

### Steps to Reproduce

I've tried with a couple of different examples, and threshold never seems to reduce. For example `sudo austin-tui python -m rich.emoji`.

**Expected behavior:** Threshold % reduces

**Actual behavior:** Nothing

**Reproduces how often:** 100% - Tried on 3 different modules in the rich repo, always the same result.

### Versions

austin 3.3.0
Monterrey 21.1 on M1 Macbook Pro

**Comment by P403n1x87** [comment]
@darrenburns apologies for getting back to you jush now. It looks like I accidentally unwatched the repo and didn't get a notification! The threshold starts at 0% by default and can only be increased with + initially. Anything _below_ the threshold is filtered out. So a threshold of 100% will show nothing. Hope that makes sense.
