### ISSUE TITLE
Unable to scroll horizontally

### ISSUE THREAD

**Issue by wgordon17** [P403n1x87/austin-tui#24]
### Description

I'm unable to scroll the TUI horizontally

**Expected behavior:** [What you expect to happen]

I should be able to scroll to the right and left

**Actual behavior:** [What actually happens]

![image](https://user-images.githubusercontent.com/22222756/200136600-f76cbb98-4515-4cf4-b2cd-3945bd9a4ad8.png)

I can't get to the stuff on the right of the screen

**Reproduces how often:** [What percentage of the time does it reproduce?]

Every time

### Versions

austin 3.4.1
austin-tui 1.2.0
MacOS 12.6

**Comment by P403n1x87** [comment]
Sadly this is not a bug, but a current limitation of the TUI. Saving the data to file and using other visualisation tools would be the way to go for now 🙁

**Comment by wgordon17** [comment]
Damn 😞 That's what I was afraid of, thanks for confirming 👍

**Comment by P403n1x87** [comment]
Or perhaps the new graph mode? The TUI is really intended for a quick "live" peek that what's running. I don't really see it as a main performance analysis tool, but happy to get actual user feedback to see if the UX can be improved!

**Comment by wgordon17** [comment]
Ultimately, my initial use case is getting a full stack trace of what's being called when, where, etc. I found the Full mode to lay that out really nicely, other than not being able to horizontally scroll 😉  The graph doesn't really capture that for me either. I resorted to using SnakeViz, which works well enough ¯\_(ツ)_/¯
