### ISSUE TITLE
Feature request: Don't require austin.exe to be on Path

### ISSUE THREAD

**Issue by cool-RR** [P403n1x87/austin-tui#5]
austin_tui can be smart enough to figure out where austin.exe is without requiring to add it to PATH, which is a bit invasive for just another tool in the toolbelt. One way to do it is by including a file ~/.austin which defines where the austin executable is, and then having austin_tui read that.

**Comment by P403n1x87** [comment]
Enhancing the way the Austin binary is discovered would make the tool more flexible. However, Austin TUI should be cross-platform as much as possible. I would introduce the following lookup order, which I think is pretty standard across platforms and other tools:

1. current working directory
3. AUSTINPATH variable
2. PATH variable

On Unix, a _run-control_ file (e.g. `.austinrc`) would also make sense, but I'm not aware of a similar "standard" for Windows.

**Comment by cool-RR** [comment]
Adding a AUSTINPATH environment variable is pretty annoying as well. I'm not sure what's the problem with using `~/.austinrc` on Windows. If you'd like to be extra Windows-y, you can store it in the appropriate folder in `~/LocalData` or however it's called, but honestly as a Windows dude I don't see much difference.
